name: api-dump
copyright: (c) 2022-2023 Simon Hengel
license: MIT

github: sol/api-dump

ghc-options: -Wall -F -pgmF=solid-pp

dependencies:
  - solid
  - haskell-base
  - containers

language: GHC2021

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DuplicateRecordFields
  - LambdaCase
  - OverloadedRecordDot
  - OverloadedStrings
  - NoFieldSelectors

build-tools: solid-pp

source-dirs: src

executable:
  main: Run.main
  when:
    condition: false
    other-modules: Paths_api_dump

tests:
  spec:
    cpp-options: -DTEST
    build-tools: hspec-discover
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec == 2.*
      - QuickCheck
    when:
      condition: false
      other-modules: Paths_api_dump
